---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.26.0
    hooks:
      - id: eslint
        args: [--fix]
        types: []
        files: (.*.js$|.*.ts$)
        additional_dependencies:
          - eslint@8.21.0
...
